# Generated by Django 4.2.13 on 2024-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('temp_in', models.FloatField()),
                ('temp_out', models.FloatField()),
                ('flow', models.FloatField()),
            ],
        ),
    ]
